[versions]
agp = "8.12.0"
composeMultiplatform = "1.8.2"
kotlinxBrowser = "0.3"
kotlin = "2.2.10"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.1" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version = "1.1.0" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
